const excelFile = document.getElementById("excelFile");

let lineChart;
let pieChart;

excelFile.addEventListener("change", handleFile);

function handleFile(e){

  const file = e.target.files[0];

  const reader = new FileReader();

  reader.onload = function(event){

    const data = new Uint8Array(event.target.result);

    const workbook = XLSX.read(data, {
      type: "array"
    });

    const sheetName = workbook.SheetNames[0];

    const worksheet = workbook.Sheets[sheetName];

    const jsonData = XLSX.utils.sheet_to_json(worksheet);

    processData(jsonData);

  };

  reader.readAsArrayBuffer(file);
}

function processData(data){

  if(!data.length){
    alert("Không có dữ liệu");
    return;
  }

  console.log(data);

  renderTable(data);

  autoGenerateDashboard(data);
}

function autoGenerateDashboard(data){

  const firstRow = data[0];

  const columns = Object.keys(firstRow);

  let dateKey = "";
  let revenueKey = "";
  let categoryKey = "";

  columns.forEach(col => {

    const lower = col.toLowerCase();

    if(
      lower.includes("date") ||
      lower.includes("day") ||
      lower.includes("ngày")
    ){
      dateKey = col;
    }

    if(
      lower.includes("revenue") ||
      lower.includes("sales") ||
      lower.includes("amount") ||
      lower.includes("doanh")
    ){
      revenueKey = col;
    }

    if(
      lower.includes("category") ||
      lower.includes("type") ||
      lower.includes("danh")
    ){
      categoryKey = col;
    }

  });

  generateKPI(data, revenueKey, categoryKey);

  if(dateKey && revenueKey){
    generateLineChart(data, dateKey, revenueKey);
  }

  if(categoryKey){
    generatePieChart(data, categoryKey);
  }

}

function generateKPI(data, revenueKey, categoryKey){

  document.getElementById("totalRows").innerText = data.length;

  let totalRevenue = 0;

  if(revenueKey){

    data.forEach(item => {
      totalRevenue += Number(item[revenueKey]) || 0;
    });

  }

  document.getElementById("totalRevenue").innerText =
    totalRevenue.toLocaleString();

  let categorySet = new Set();

  if(categoryKey){

    data.forEach(item => {
      categorySet.add(item[categoryKey]);
    });

  }

  document.getElementById("totalCategory").innerText =
    categorySet.size;

}

function generateLineChart(data, dateKey, revenueKey){

  const labels = data.map(item => item[dateKey]);

  const values = data.map(item =>
    Number(item[revenueKey]) || 0
  );

  if(lineChart){
    lineChart.destroy();
  }

  const options = {

    chart:{
      type:'line',
      height:350
    },

    series:[{
      name:'Revenue',
      data:values
    }],

    xaxis:{
      categories:labels
    }

  };

  lineChart = new ApexCharts(
    document.querySelector("#lineChart"),
    options
  );

  lineChart.render();
}

function generatePieChart(data, categoryKey){

  const categoryMap = {};

  data.forEach(item => {

    const category = item[categoryKey];

    if(!categoryMap[category]){
      categoryMap[category] = 0;
    }

    categoryMap[category]++;

  });

  const labels = Object.keys(categoryMap);

  const values = Object.values(categoryMap);

  if(pieChart){
    pieChart.destroy();
  }

  const options = {

    chart:{
      type:'pie',
      height:350
    },

    labels:labels,

    series:values

  };

  pieChart = new ApexCharts(
    document.querySelector("#pieChart"),
    options
  );

  pieChart.render();
}

function renderTable(data){

  const tableHead = document.querySelector("#dataTable thead");
  const tableBody = document.querySelector("#dataTable tbody");

  tableHead.innerHTML = "";
  tableBody.innerHTML = "";

  const columns = Object.keys(data[0]);

  let headRow = "<tr>";

  columns.forEach(col => {
    headRow += `<th>${col}</th>`;
  });

  headRow += "</tr>";

  tableHead.innerHTML = headRow;

  data.forEach(row => {

    let tr = "<tr>";

    columns.forEach(col => {
      tr += `<td>${row[col] || ""}</td>`;
    });

    tr += "</tr>";

    tableBody.innerHTML += tr;

  });

}
